export const BATTERY_BRIGHTNESS_SETTING = "battery-brightness"
export const POWER_BRIGHTNESS_SETTING = "power-brightness"
export const BATTERY_THEME_SETTING = "battery-theme"
export const POWER_THEME_SETTING = "power-theme"
export const BATTERY_KEYBOARD_SETTING = "battery-keyboard"
export const POWER_KEYBOARD_SETTING = "power-keyboard"
